#!/usr/bin/env python

import sys
with open(sys.argv[1]) as fp:
    contents = fp.read()

sys.stdout.write(contents)
# sys.stdout.write('define(["ember"], function(Ember){\n')
# sys.stdout.write('  ' + contents)
# sys.stdout.write('});\n')
